language: php
php:
  - 5.6
  - 7.0
  - hhvm
  - nightly
services:
  - mariadb
before_script:
  - mysql -e 'CREATE DATABASE mustard_test'
install:
  - composer install --no-interaction --prefer-source
